### ISSUE TITLE
Panic Button

### ISSUE THREAD

**Issue by jhhl** [dxinteractive/xenpaper#21]
When using really long bpms (I typically use 1 or less...), the "stop" button won't stop the sound until the clock has run out on the beat! MIDI people are used to a "panic button"  and something like that would be good here.
Other forms of setting the time like msecs:nnn or secs:nn would be nice too.

**Comment by dxinteractive** [comment]
Ah good point, I can definitely add this.

For setting the time, do you mean setting the position of the playhead, setting the position of a note, or setting the duration of a note, or multiple of those / something else?

**Comment by jhhl** [comment]
The time setting would just be another way of expressing beats other than bpms.

**Comment by dxinteractive** [comment]
Great idea, I've added that here #27

**Comment by dxinteractive** [comment]
While I haven't added a panic button per se, I've made the stop button stop the audio rather than just the playhead in `1.2.0`. I may reopen if the need for a panic button arises in future, but what I have here should negate the need according to tonejs.

**Comment by jhhl** [comment]
Thanks!
