### ISSUE TITLE
Add "Take this sequence modulo n" command

### ISSUE THREAD

**Issue by Marc-Winner** [dxinteractive/xenpaper#28]
Now the sequences are manually written by user, this feature will allow to use arbitrary growing sequences (e.g. from [OEIS](https://oeis.org/)) without breaking out of hearing range.

Example:
[Ulam sequence under 100 taken from internet and taken modulo 13 in BP](https://xenpaper.com/?fbclid=IwAR3NZB9SKQ-pZnX6QPutQQil5KOyPcKv-sSdTMoTPQNjKOHYsqelUxFV6gw#%23%20ulam%20sequence%20mod%2013%20under%201000%20in%20Bohlen-Pierce%0A(osc:sine)%7B13ed3%7D%0A1,%202,%203,%204,%206,%208,%2011,%200,%203,%205,%200,%202,%2010,%2012,%208,%209,%201,%205,%2010,%204,%207,%2012,%204,%209,%206,%208,%2011,%202,%2010,%209,%201,%208,%202,%205,%2012,%206,%208,%2011,%200,%207,%202,%2011,%201,%2011,%200,%202,%204,%207,%209,%206,%2011,%200,%200,%209,%2010,%204,%207,%2012,%201,%203,%205,%207,%2012,%206,%205,%200,%2010,%2012,%206,%209,%2011,%200,%202,%205,%2012,%209,%201,%202,%204,%203,%208,%202,%204,%2011,%200,%207,%209,%200,%204,%207,%209,%201,%200,%203,%209,%205,%2010,%209,%2012,%201,%206,%205,%207,%204,%206,%2011,%2010,%201,%203,%205,%207,%201,%202,%204,%203,%206,%208,%207,%209,%208,%204,%200,%208,%2011,%203).

**Comment by dxinteractive** [comment]
Hi, I'm considering adding a feature for users to add javascript to programatically generate tunes rather than having to type them, which could definitely do something like this and *much* more. I'd like to keep the xenpaper grammar itself as 1:1 to how it is played as possible.

**Comment by dxinteractive** [comment]
I've added #31 to note down the generative code idea I mentioned.

**Comment by Marc-Winner** [comment]
> Hi, I'm considering adding a feature for users to add javascript to programatically generate tunes rather than having to type them, which could definitely do something like this and _much_ more. I'd like to keep the xenpaper grammar itself as 1:1 to how it is played as possible.

It's even better, thank you!
