### ISSUE TITLE
Add button/short-cut to activate a specific line of code

### ISSUE THREAD

**Issue by Marc-Winner** [dxinteractive/xenpaper#30]
Now all the code is activated sequentially in order.
But sometimes it is of use to sound only one specific line of code at a time.
It gives freedom to decide what to play not using pesky commenting / uncommenting.
It can be implemented as a separate button activating the line on the cursor or a short-cut (like in Supercollider).

**Comment by dxinteractive** [comment]
Yeah I'm very keen for this - covered by this task #1. I'll close as this is a duplicate, thanks for logging this!
