### ISSUE TITLE
[Question] multiple tracks at the same time?

### ISSUE THREAD

**Issue by nkint** [dxinteractive/xenpaper#46]
Hi! I love this!
I have a question as a super-noob of webmidiapi or music in the browser.

Have you ever thought to permit the user to play multiple tracks simultaneously in xenpaper?

**Comment by nkint** [comment]
(I'd like to play in xen paper two tracks simultaneously shifting manually one of them, something like this:

https://www.youtube.com/watch?v=lzkOFJMI5i8

)

**Comment by dxinteractive** [comment]
Hi, yep it's something I'd like to add as a priority. I already have a ticket for it here, so I'll close this issue in favour of the existing one #8
