### ISSUE TITLE
`m` in comment sometimes causes parsing error

### ISSUE THREAD

**Issue by bgins** [dxinteractive/xenpaper#47]
Hello :wave:.

I noticed that in some cases the character `m` in a comment triggers a parsing error. For example:

```
# Ptolemy's Diatonic Scales
{1/1 21/20 7/6 4/3 3/2 63/40 7/4}
0 1 2 3 4 5 6 7-

# Ptolemy's Tense Diatonic
{1/1 16/15 6/5 4/3 3/2 8/5 9/5}
0 1 2 3 4 5 6 7-
```

In this case, if the `m` is removed from the second instance of `Ptolemy's`, parsing succeeds.

This is an excellent app, and I have been enjoying it quite a lot. Thank you for making it! :heart:

**Comment by dxinteractive** [comment]
Oh how bizarre! I'll definitely need to fix this.

**Comment by dxinteractive** [comment]
Think I found it, looks like there's a missing `^` at the start of the regex that matches the `m` in the scale group prefixes liek `{m0 1}`. https://github.com/dxinteractive/xenpaper/blob/main/packages/xenpaper-ui/src/data/grammar.ts#L341

I'll try get a small release through soon with the fix.

**Comment by bgins** [comment]
Awesome thanks! :pray:

**Comment by dxinteractive** [comment]
Hi @bgins , I believe this is fixed now as of https://github.com/dxinteractive/xenpaper/releases/tag/1.4.1. Sorry it took so long!

**Comment by bgins** [comment]
Hey, just tried it out, and it's working great! Here's a paper with a [set of ancient Greek enharmonic tunings](https://xenpaper.com/#%23_A_set_of_tunings_from_Cris_Forster's_Musical_Mathematics.%0A%23_From_the_table_titled_%22Ptolemy's_Catalog_of_Scales%22.%0A%23_Chronicle_Books%2C_2010%2C_p._330.%0A%0A(bpm%3A90)%0A(osc%3Asine2)%0A%0A%23_Archytas_Enharmonic%0A%7B1%2F1_28%2F27_16%2F15_4%2F3_3%2F2_14%2F9_8%2F5%7D%0A0_1_2_3_4_5_6_7-%0A%0A%23_Aristoxenus_and_Eratosthenes_Enharmonic%0A%7B1%2F1_40%2F39_20%2F19_4%2F3_3%2F2_20%2F13_30%2F19%7D%0A0_1_2_3_4_5_6_7-%0A%0A%23_Aristoxenus_and_Eratosthenes_Enharmonic%0A%7B1%2F1_32%2F31_16%2F15_4%2F3_3%2F2_48%2F31_8%2F5%7D%0A0_1_2_3_4_5_6_7-%0A%0A%23_Ptolemy_Enharmonic%0A%7B1%2F1_46%2F45_16%2F15_4%2F3_3%2F2_23%2F15_8%2F5%7D%0A0_1_2_3_4_5_6_7-). Extensive use of `m` in the comments throughout.

Thanks again for the great work on this app!
