### ISSUE TITLE
Crashes sometimes when changing edo

### ISSUE THREAD

**Issue by sus1357** [dxinteractive/xenpaper#59]
For example when you input
`{40edo}[0]`
and then erase that '4' to replace it with something else (`50edo` for ex.) it crashes besause of temporary `{0edo}[0]` (zero-edo) state

Another example:
`(bpm:5){r200Hz}{4000edo} [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]` works perfectly, but
`(bpm:5){r200Hz}{000edo} [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]` makes it crash again

**Comment by dxinteractive** [comment]
Sorry I missed this, this should now be fixed.
